void despedida(){
    system("cls");
    barra(100);sl(1);
    barra(27);
    printf("HASTA LUEGO, GRACIAS POR UTILIZAR EL PROGRAMA");
    barra(28);sl(1);
    barra(100);sl(1);
    barra(2);espacios(29);
    printf("UNIVERSIDAD NACIONAL AUT%cNOMA DE M%cXICO",oO,eE);
    espacios(28);barra(2);sl(1);
    barra(2);espacios(29);
    printf("FACULTAD DE ESTUDIOS SUPERIORES ACATL%cN", aA);
    espacios(28);barra(2);sl(1);
    barra(2);espacios(38);
    printf("M%cTODOS NUM%cRICOS II",eE,eE);
    espacios(38);barra(2);sl(1);
    barra(2);espacios(41);
    printf("PAQUETE FINAL");
    espacios(42);barra(2);sl(1);
    barra(2);espacios(5);
    printf("Miembros del equipo:");
    espacios(71);barra(2);sl(1);
    barra(2);espacios(10);
    printf("%c%clvarez Cortes Kevin Alejandro", 126, aA);
    espacios(55);barra(2);sl(1);
    barra(2);espacios(10);
    printf("%cBautista Gaona Luis Eduardo",126);
    espacios(58);barra(2);sl(1);
    barra(2);espacios(10);
    printf("%cFlores Hern%cndez Itzel",126, a);
    espacios(63);barra(2);sl(1);
    barra(2);espacios(10);
    printf("%cFlores Velasco Jos%c Juan",126,e);
    espacios(61);barra(2);sl(1);
    barra(100);printf("\n");
    system("pause");
    system("cls");
}

void bienvenida(){
    system("cls");
    barra(100);sl(1);
    barra(45);
    printf("BIENVENIDO");
    barra(45);sl(1);
    barra(100);sl(1);
    barra(2);espacios(29);
    printf("UNIVERSIDAD NACIONAL AUT%cNOMA DE M%cXICO",oO,eE);
    espacios(28);barra(2);sl(1);
    barra(2);espacios(29);
    printf("FACULTAD DE ESTUDIOS SUPERIORES ACATL%cN", aA);
    espacios(28);barra(2);sl(1);
    barra(2);espacios(38);
    printf("M%cTODOS NUM%cRICOS II",eE,eE);
    espacios(38);barra(2);sl(1);
    barra(2);espacios(41);
    printf("PAQUETE FINAL");
    espacios(42);barra(2);sl(1);
    barra(2);espacios(5);
    printf("Miembros del equipo:");
    espacios(71);barra(2);sl(1);
    barra(2);espacios(10);
    printf("%c%clvarez Cortes Kevin Alejandro", 126, aA);
    espacios(55);barra(2);sl(1);
    barra(2);espacios(10);
    printf("%cBautista Gaona Luis Eduardo",126);
    espacios(58);barra(2);sl(1);
    barra(2);espacios(10);
    printf("%cFlores Hern%cndez Itzel",126, a);
    espacios(63);barra(2);sl(1);
    barra(2);espacios(10);
    printf("%cFlores Velasco Jos%c Juan",126,e);
    espacios(61);barra(2);sl(1);
    barra(100);printf("\n");
    system("pause");
    system("cls");
}

void menu(){

    barra(100);sl(1);
    barra(2);espacios(2);
    printf("En este Paquete Final tendremos el conjunto de todos los programas realizados durante el");
    espacios(6);barra(2);sl(1);
    barra(2);espacios(2);
    printf("curso, es decir:");
    espacios(78);barra(2);sl(1);
    barra(2);espacios(10);
    printf("1.- Sistema de Ecuaciones no Lineales");
    espacios(49);barra(2);sl(1);
    barra(2);espacios(10);
    printf("2.- Interpolaci%cn y Ajuste de Curvas",o);
    espacios(50);barra(2);sl(1);
    barra(2);espacios(10);
    printf("3.- Diferenciaci%cn e Integraci%cn", o, o);
    espacios(54);barra(2);sl(1);
    barra(100);sl(1);
}

void menuCase1(){
    barra(100);sl(1);
    barra(31);
    printf("1.- SISTEMA DE ECUACIONES NO LINEALES");
    barra(32);sl(1);
    barra(100);sl(1);
    barra(2);espacios(2);
    printf("Escoja uno de los cuatro sistemas de ecuaciones integrado en este programa");
    espacios(20); barra(2);sl(1);
    barra(2);espacios(10);
    printf("1.-");
    espacios(83); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c1(x, y)=x%c+xy-10=0",f,253);
    espacios(64); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c2(x, y)=y+3xy%c-50=0",f,253);
    espacios(63); barra(2);sl(1);
    barra(2);espacios(10);
    printf("2.-");
    espacios(83); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c1(x, y)=x%c+y%c-9=0",f,253,253);
    espacios(65); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c2(x, y)=-e%c-2y-3=0",f,158);
    espacios(64); barra(2);sl(1);
    barra(2);espacios(10);
    printf("3.-");
    espacios(83); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c1(x, y, z)=2x%c-4x+y%c+3z%c+6z+2=0",f,253,253,253);
    espacios(51); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c2(x, y, z)=x%c+y%c-2y+2z%c-5=0",f,253, 253, 253);
    espacios(55); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c3(x, y, z)=3x%c-10x+y%c-3z%c+8=0",f,253, 253, 253);
    espacios(53); barra(2);sl(1);
    barra(2);espacios(10);
    printf("4.-");
    espacios(83); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c1(x, y, z)=x%c-4x+y%c=0",f,253,253);
    espacios(61); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c2(x, y, z)=x%c-x-12y+1=0",f,253);
    espacios(59); barra(2);sl(1);
    barra(2);espacios(13);
    printf("%c3(x, y, z)=3x%c-10x+y%c-3z%c+8=0",f,253, 253, 253);
    espacios(53); barra(2);sl(1);
    barra(2);espacios(10);
    printf("5.- Salir del Programa");
    espacios(64); barra(2);sl(1);
    barra(100);sl(1);
    printf(">");
}